exports.el = {
    acceptCookiesBtn: 'button#onetrust-accept-btn-handler',
    iframe: '#widget',
    containerHeader: '.Container_header__kc6DP',
    youPayInput: 'input[name=source]',
    youGetInput: 'input[name=target]',
    totalAmountValue: '.CollapsibleFeesCard_totalAmountRow__cNIuA .CollapsibleFeesCard_overflow__PyrbR',
    totalFeesValue: '.CollapsibleFeesCard_totalFeesRow__FR2fG .CollapsibleFeesCard_overflow__PyrbR',
    assetSelectionBtn: 'button[title="Selecionar ativo"]',
    currencySelectionBtn: 'button[title="Selecionar moeda"]',
    noResultsFoundP: '.Select_groupLabel__pcXQK',
    assetNameAbbreviation: 'button[title="Selecionar ativo"] span.Currency_code__n9QXa',
    exchangeRateText: 'div.ExchangeRateBadge_exchangeRateBadge__P72i_ p.ExchangeRateBadge_rate__D_qYC',
    totalFees: '.CollapsibleFeesCard_toggleFees___s9F2',
    feesLabel: '.CollapsibleFeesCard_feeLabel__IAu89 span',
    noFeesLabel: '.CollapsibleFeesCard_noFees__HP689 span',
    errorMessage: 'p.CurrencyInput_error__vEWRm',
    assetSearchInput: '[data-testid="asset-search-input"]',
    currencySearchInput: '[data-testid="asset-search-input"]',
    asset: '.Currency_item__DETdh[role=button]'
}